sudo: required

language: python
python: 2.7

services:
  - docker

env:
  - TOX_ENV=py27

git:
  submodules: true

before_install:
  - make docker_install
  - travis wait 45 make docker_build
  - make docker_run
  - sleep 30

install:
  - make install
