sudo: required

language: python
python: 2.7

services:
  - docker

git:
  submodules: false

before_install:
  - wget https://raw.githubusercontent.com/galaxyproject/galaxy-flavor-testing/master/Makefile
  - make docker_install
  - make docker_build
  - make docker_run
  - sleep 300

install:
  - make install

script:
  - make test_api
  - make test_ftp
  - make test_bioblend
